# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION_RECEIVED', 'Registration received'), ('RESERVATION_CONFIRMED', 'Reservation confirmed'), ('PAYMENT_CONFIRMED', 'Payment confirmed'), ('PAYMENT_FAILED', 'Payment failed'), ('REFUND_PROCESSED', 'Refund processed'), ('RACE_PACK_COLLECTION', 'Race pack collection'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=40),
        ),
    ]
