# Generated by Django 6.1 on 2026-08-12 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_start', models.DateTimeField(blank=True, null=True)),
                ('registration_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_categories', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('RESERVED', 'Reserved (Pay Later)'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded')], default='PENDING_PAYMENT', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='participants.participant')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='registrations.registrationcategory')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Registration Form', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_form', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Long Text'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('SELECT', 'Select'), ('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('FILE', 'File')], max_length=30)),
                ('key', models.SlugField(max_length=100)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='registrations.registrationform')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='registrationcategory',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='unique_event_registration_category'),
        ),
        migrations.AddConstraint(
            model_name='registrationfield',
            constraint=models.UniqueConstraint(fields=('form', 'key'), name='unique_registration_field_key'),
        ),
    ]
