# Generated by Django 6.1 on 2026-09-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_created_by_registration_created_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created_via',
            field=models.CharField(choices=[('PUBLIC', 'Public site'), ('ADMIN', 'Admin dashboard'), ('UNKNOWN', 'Unknown (before this was tracked)'), ('LENCO_MIGRATION', 'Migrated from Lenco')], default='UNKNOWN', max_length=20),
        ),
    ]
