# Generated by Django 6.1 on 2026-08-12 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.paymentaccount'),
        ),
        migrations.AddField(
            model_name='eventmembership',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_event_slug_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='eventmembership',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_membership'),
        ),
    ]
