# Generated by Django 6.1 on 2026-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_confirmed_registrations',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
