# Generated by Django 6.1 on 2026-08-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Card'), ('MTN_MONEY', 'MTN Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('ZAMTEL_KWACHA', 'Zamtel Kwacha'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMERICAN_EXPRESS', 'American Express'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=50),
        ),
    ]
